### ISSUE TITLE
Stream never ends

### ISSUE THREAD

**Issue by soyuka** [tmpfs/cparse#1] opened 2016-02-29 15:53 UTC
Events `finish` or `end` are never called.

**Comment by tmpfs** [comment] 2016-03-01 01:18
I see that the `finish` event is firing but the `end` event is not.

The stream is a duplex transform stream so I would expect both events to fire.

To test the `finish` event uncomment https://github.com/tmpfs/cparse/blob/master/test/spec.js#L19.

And run `node test/spec test/example`, I'll look in to the `end` event but you would want to listen to `finish` to be sure all comments have been parsed.

If you still don't see the `finish` event fire please provide a test case the reproduces the issue.

Thanks for letting me know!

**Comment by tmpfs** [comment] 2016-03-01 01:19
Behaviour is the same for me in `0.12` and `4.0`.

**Comment by tmpfs** [comment] 2016-03-01 01:37
Test case for the finish event added in da911817f5ef3eb0f860adf393944f35d14911e5.

**Comment by tmpfs** [comment] 2016-03-01 01:48
The `end` event is not firing because the readable side of the parser stream is not being consumed, if you pipe the returned parser stream, the end event will fire :)

**Comment by tmpfs** [comment] 2016-03-01 02:56
Test spec for `end` event added in a2b1538a0043d8073189d29e890d4cbbb1f71bc8.

**Comment by tmpfs** [comment] 2016-03-01 02:58
You can now consume the readable side by calling `stringify()` on the parser, docs:

https://github.com/tmpfs/cparse#stringify

And then pipe that to an `fs.createWriteStream` call, I'll likely add a `write|save` call so that you can do:

```javascript
parser.load('index.js').stringify().save('index.ast.json.log');
```

**Comment by tmpfs** [comment] 2016-03-01 02:59
Closing as not an issue.

**Closed by tmpfs** 2016-03-01 02:59 UTC
